site_name: "Elena Framework for cryptocurrencies trading bots documentation"
repo_url: https://github.com/Pasta-fantasia/elena-docs
edit_uri: edit/main/docs/
extra:
  version: 1.0.0
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/fransimo
    - icon: fontawesome/brands/instagram
      link: https://instagram.com/fransimo_nft
    - icon: fontawesome/brands/github
      link: https://github.com/fransimo/
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/fransimoart
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/fransimo
    - icon: fontawesome/solid/paper-plane
      link: mailto:contact@fransimo.info
    - icon: fontawesome/brands/mailchimp
      link: https://fransimo.us10.list-manage.com/subscribe?u=4e708ed8e3a29fc5dc139a011&id=7546e4b3aa

copyright: Apache License - 2022 - Fran Simó

plugins:
  - git-revision-date
  - print-site:
      add_to_navigation: false
      print_page_title: 'Print Site'
      add_print_site_banner: true
      # Table of contents
      add_table_of_contents: true
      toc_title: 'Table of Contents'
      toc_depth: 6
      # Content-related
      add_full_urls: false
      enumerate_headings: true
      enumerate_figures: true
      add_cover_page: true
      cover_page_template: ""
      path_to_pdf: ""
      include_css: true
      enabled: true
      exclude:

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - tables
  - attr_list
  - md_in_html

nav:
  # - 'Conexión': 'stream.md'
  # - '¡Hola mundo!': 'hello_world.md'
  - 'Install':
    - 'Pure Python': '01_install/pure_python.md'
    - 'Docker': '01_install/docker.md'
  - 'Config':
    - 'Exchanges': '02_config/exchanges.md'
    - 'Telegram': '02_config/telegram.md'
  - 'Strategies':
      - 'Use cases and overview': '03_strategies/use_cases.md'
      - 'Configuration by example': '03_strategies/configuration_by_example.md'
      - 'Experiments':
        - 'DCA_Conditional_Buy_LR_with_TrailingStop': '03_strategies/DCA_Conditional_Buy_LR_with_TrailingStop/index.md'
  - 'Roadmap': '04_roadmap/index.md'
  - 'Resources': 'resources.md'
  - 'Donate': 'donate.md'
  - 'About':
      - 'Team': 'about/team.md'
      - 'License': 'license.md'
      - 'Release Notes': 'release-notes.md'
  - 'Print': '/print_page/'

extra_css:
#  - stylesheets/extra.css

theme:
  # name: mkdocs
  # name: bootstrap386
  # name: readthedocs
  # name: ivory
  # name: gitbook
  logo: assets/logo.png
  language: es
  name: material

  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - toc.integrate
  palette:
    - scheme: default
      primary: grey
      toggle:
        icon: material/lightbulb-outline
        name: Switch to dark mode
    - scheme: slate
      primary: grey
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode


  locale: es
  navigation_depth: 10
  prev_next_buttons_location: both
  collapse_navigation: False